### ISSUE TITLE
Designing

### ISSUE THREAD

**Issue by malarvi** [BobBowles/django-diary#1]
Hi,
I'm New to Django. I'm Executing Diango-diary in local Syetem. But i can't optimize the design.If i want to add any input fields in login page or Register page where i want to change code.

**Comment by BobBowles** [comment]
Hi Malarvi

If you have downloaded the app from Github you have access to all the code locally so you can change it how you want. 

It has been a while since I was active developing Django-Diary but I tried to structure it in a 'conventional' way. The data model is defined in the diary/models.py file, for example. Changing the login and/or registration is a bit more fiddly, because I chose to subclass the User to create Customer. You will find the forms used in diary/admin.py

If you have worked through the online tutorials, like DjangoGirls for example, that should give you enough knowledge to know where to start. For the rest, I find StackExchange and the Django online documentation very good.

If you need more specific help I will need to know what you are trying to do.

Best wishes   Bob

**Comment by malarvi** [comment]
Hi,
Thank you for your suggestions.I have one more error.That is while Admin add entry in Administrator site it shows the following **'NoneType' object has no attribute 'is_staff'** .

**Comment by BobBowles** [comment]
That sounds like a typical Python error when a null object is passed as an argument. Possibly something was not initialized correctly. More information should be in the stack trace.

**Comment by malarvi** [comment]
I need to enable and add task reminders in current day also.I enabled current day but while add reminders it shows need to book ahead.So I need your help to change that.

**Comment by BobBowles** [comment]
The reminders information is provided by the reminders function in views.py. The function currently generates a queryset of the relevant entries for today and tomorrow, discounting the ones that fall before the present time.  Thus, if the page is generated at 13:30 on 3rd May, 2017, the entries in the queryset will include only those entries with a start date/time greater than 13:30, May 3rd 2017, and strictly less than 5th May, 2017. If you want to change what it does you need to change the queries in that function.
